/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
	
    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1.1-jre")
	
	implementation("com.microsoft.signalr:signalr:6.0.0")
}

application {
    // Define the main class for the application.
    mainClass.set("App")
}

tasks.getByName<JavaExec>("run") {
    standardInput = System.`in`
}